### ISSUE TITLE
Support Include

### ISSUE THREAD

**Issue by dane-harnett** [zimmo-be/twig-loader#1]
Hi,

Are you still looking at adding `include` support?

**Comment by webberig** [comment]
Yes, I was planning adding it as soon as I came across an implementation in my own projects.

**Comment by dane-harnett** [comment]
That would be great as I would love to trial migration to using webpack and twig.

**Comment by webberig** [comment]
I added "include" support and released it as version 0.1.2. Good luck! :-)
