### ISSUE TITLE
not safe use absolute path as id template

### ISSUE THREAD

**Issue by DragorWW** [zimmo-be/twig-loader#12]
after compile twig, in js id contain my absolute path file, it not safe

``` js
twig({id:"/var/www/project/frontend/components/block/template.twig" ...
```

`twig-loader index.js issue string`

``` js
var id = require.resolve(this.resource)
```

**Comment by webberig** [comment]
Must research if process.cwd can be used to calculate a relative path...

**Comment by DragorWW** [comment]
@webberig We will can in product mode set Id of twig template as hash by path.
add setting to twig-loader "path".
and set it to "[resourcePath]" or "[hash]" in develop or product mode.

**example:**
```js
{
    test: /\.twig$/,
    loader: function () {
        return process.env.NODE_ENV === 'development' ? 'twig?path=[resourcePath]' : 'twig?path=[hash]';
    }())
},
```

**Comment by webberig** [comment]
Started work in PR #17 ... Needs further testing, any feedback is much appreciated!
