### ISSUE TITLE
Look into include

### ISSUE THREAD

**Issue by zalox** [zimmo-be/twig-loader#19]
Hi,

I was thinking of looking into supporting include and import. Is it anything blocking these features?

**Comment by webberig** [comment]
Can you elaborate ? Include and import are already supported.

**Comment by zalox** [comment]
I was reading your README.md and saw this: `When you extend another view, it will also be added as a dependency. Include and Import are not yet supported (check back soon).`  Maybe you forgot to remove this? https://github.com/zimmo-be/twig-loader/blame/master/README.md#L46

**Comment by webberig** [comment]
Ah you're right, I forgot about that. I can confirm that include, import,
extend and embed are supported. I'll update the readme file.
Op 11-jul.-2016 19:19 schreef "Jørgen Lien Sellæg" <notifications@github.com
