### ISSUE TITLE
Combine with other loaders

### ISSUE THREAD

**Issue by auburus** [zimmo-be/twig-loader#21]
First of all, I really (really!) like your loader, and if I'm able to overcome this issue I'll have a team of 5 developers happy.

So, this loader transforms Twig files to a js function, that you have to call to obtain the html. And what should be extra nice is something that transforms from twig to html (as I understood that a twig loader would do). But, in that case, given how it's implemented right now, you miss the oportunity to pass Twig
variables to it.

What I propose, and tell me how that sounds, is being able to set those variables directly from the loader config, like...

```js
//webpack.config.js

//...
module: {
  loaders: [
    test: /\.twig$/,
    loader: 'twig'
  ]
},
twigLoader: {
  variables: {
    var1: "value 1",
    var2: "value 2"
  }
}
```
(I proposed this because the sassLoader has a config option that works like this, but any alternative similar to that is good enough.

That will allow to pipe the loader results to the html loader, or a Plugin that generates an Html file (which is what I'm looking for).

If, there is a better way to achieve this result, please, I'm a backend dev who's trying to figure out the frontend world (and it's a little overwhelming, haha).

**Comment by webberig** [comment]
Hi!

Please take a look at this section of the webpack documentation:
http://webpack.github.io/docs/how-to-write-a-loader.html#do-only-a-single-task

Firstly, it will explain why we won't implement what you're asking in this loader, as it would violate the single task rule.

But coincidently, it will also gives an example for your use case. The apply-loader will probably do what you want.

**Comment by auburus** [comment]
Oh, my bad, so sorry.

It does much more sense using concrete loaders, and the apply loader saved the day, so thanks for your suggestion.

I'll leave this here in case anyone else is struggling with the same (or, if you prefer, I can make a pull request to put it in the docs, up to you).

```js
// File: twigVariables.js
module.exports = {
  name: 'Mufasa'
}
```
```js
// File webpack.config.js

var twigVariables = require('./twigVariables.js');

module.exports = {
  // ...

  module: {
    loaders: {
      {
        test: /\.twig$/,
        loader: "apply?{ obj: " + twigVariables + "}!twig"
      }
    }
  }
}
```

**Comment by nickkessler** [comment]
+1 

Would love to use this twig plugin but I need to pipe with the html load so I can integrate with the url loader, for images.

Any help greatly appreciated.

**Comment by webberig** [comment]
This loader's purpose is to COMPILE twig templates, not actually RENDER them. If you are trying to render HTML during build-time, this loader is not the tool you need.

Since I don't have use cases for this in my own projects, I can't provide a working example, but - in theory - you should create a JS file that imports TwigJS directly (not the loader) and renders a given template. After that, you can use [Apply-loader](https://github.com/mogelbrod/apply-loader) to execute the rendering and add the result to your webpack chunks.
