### ISSUE TITLE
pass twig compile params

### ISSUE THREAD

**Issue by DragorWW** [zimmo-be/twig-loader#22]
i use cross render twig (php and js).
in php twig by default enable autoescape, in twig.js it need enable.

i create [fork witch path](https://github.com/DragorWW/twig-loader/commit/92e2775fe961a140d66cecf3bba0b464f2496b26) and use them.

How to add it params in twig-loader?
1) i can make pr with my path
or
2) pass param from loader options and create pr

**Comment by webberig** [comment]
Webpack 2 has made significant changes to how you can add options to a loader or plugin. Perhaps we can look into that?

**Comment by tremby** [comment]
Published as `@tremby/twig-loader`
