### ISSUE TITLE
twig-loader & Typescript & ES6 Imports ?

### ISSUE THREAD

**Issue by daslicht** [zimmo-be/twig-loader#24]
Hi, 
is there a way to use ts-loader with TypeScript, please ?
How to do imports ?

I tried something like this but it fails:
```
import * from "./dialog.twig"
```

**Comment by webberig** [comment]
What about this syntax ?

    import tpl from "./dialog.twig"

**Comment by daslicht** [comment]
I get cannot find  ```"./dialog.twig"``` so it is about this part  :/

**Comment by webberig** [comment]
Take a look at this:
https://github.com/Microsoft/TypeScript/issues/2709

Let us know if this helped!

**Comment by daslicht** [comment]
Thank you !

**Comment by piernik** [comment]
I still don't know how to import twig file.
Can anyone give working example?

**Comment by megahertz** [comment]
@piernik 
create typing *twig.d.ts* in your project
```typescript
declare module "*.twig" {
  const template: (variables?: object) => string;
  export = template;
}
```

then
`import * as indexView from "./views/index.twig";`

**Comment by renestalder** [comment]
This is what worked for me, combined with the typing file above.

```ts
import indexView from "./views/index.twig";
```
