### ISSUE TITLE
Does webpack 2 supported?

### ISSUE THREAD

**Issue by radiocity** [zimmo-be/twig-loader#25]
I want to migrate from gulp to webpack 2. Does twig-loader supports webpack 2 already?
Thank you.

**Comment by webberig** [comment]
Haven't tried it yet, so no idea...

**Comment by pepf** [comment]
Same here, here's another error log:
```
ERROR in ./application/twig/notification_popup.twig
Module not found: Error: Can't resolve 'twig' in './application/twig'
 @ ./application/twig/notification_popup.twig 1:11-26
 @ ./js/modules/common/views/notificationpopup.js
```
Will do some more digging, hopefully I can get this to work. :)

**Comment by wadouk** [comment]
I made all my path relatives, and it's work better. i don't find a way to define a global lookup path.
I think the "can't resolve twig" is an other issue

**Comment by pepf** [comment]
Yeah it was a different issue indeed. To solve that I could just add a twig entry to the webpack provideplugin to make it available in the compiled templates:
```js
    // Something along these lines
    new webpack.ProvidePlugin({
      $: 'jquery',
      Backbone: 'backbone',
      _: 'underscore',
     twig: 'twig'
    }),
```

**Comment by webberig** [comment]
We managed to upgrade to webpack 3.8 without requiring any changes to twig-loader. Until there's proof of an actual change required to make it work, I will close this issue.
