### ISSUE TITLE
Export template directly 

### ISSUE THREAD

**Issue by wadouk** [zimmo-be/twig-loader#32]
https://github.com/zimmo-be/twig-loader/blob/eb5212af86782623513782494e9ef554eb0be647/lib/compiler.js#L52

It will be interesting to export the template instead of export the execution of render function

**Comment by webberig** [comment]
The way twig-loader works is consistent with other template-engine loaders, so we don't want to change that. Please elaborate on why this would be useful, maybe an alternative solution can be presented.
