### ISSUE TITLE
Filters and functions

### ISSUE THREAD

**Issue by cbo317110** [zimmo-be/twig-loader#33]
Right now, i'm trying add twig on my vue.js environment, but i see myself stuck on this fog.
Can i adding some filters or functions like bellow

``` twig
{{ var|filter }} 
```

``` twig
{{ function(var) }} 
```

**Comment by webberig** [comment]
Check out the Twig.JS documentation about this topic:
https://github.com/twigjs/twig.js/wiki/Extending-twig.js

**Comment by tremby** [comment]
This isn't working as I expect it to.

In my webpack configuration, before returning the configuration object, I'm doing this:

```js
const Twig = require("twig");

// Extend Twig
Twig.extendFilter("backwords", (value) => {
  return value.split(' ').reverse().join(' ');
});
```

If I try to use the filter in a template loaded by twig-loader, I get an error saying the filter `backwords` doesn't exist.

I put some logs in twig.js itself to see if I could trace the issue. The filter is added to the `Twig.filters` map when I ask it to, but then when the templates are actually rendered the filter no longer exists -- I guess Twig has been reinitialized at some point.

I tried instead putting the Twig extension code in one of my JS files HtmlWebpackPlugin is loading -- these are the files which import twig files (via twig-loader). It works after I do this. But I find this messy -- it would be nicer to specify the twig configuration/extensions in the webpack configuration.

Maybe the loader could accept a closure to run with Twig in context?

**Comment by tremby** [comment]
I've looked further into my proposal (last line of previous message). I don't think it's possible, unfortunately, since lib/compiler.js outputs a string of fresh JS which would need to include the Twig extension logic. And as far as I know there's no way to stringify a JS function. @webberig, any comment?

**Comment by tremby** [comment]
Found a way, similar to how Twig itself is imported in the generated code.

**Comment by webberig** [comment]
This should just work:

```
const Twig = require("twig"),

Twig.extendFilter("surface", function (value) {
    var SurfaceFormatter = require("Utils/SurfaceFormatter"),
        surface = new SurfaceFormatter();
    return surface.format(value);
});

const tpl = require('myTemplate.html.twig'); // template that uses the surface filter
tpl();
```

**Comment by tremby** [comment]
Sure, that works from that JS file, but not from the webpack configuration. If you don't have such a JS file as yours (such as when twig-loader is invoked by a plugin, not by you in your JS files requiring a twig template) there's nowhere to write this `Twig.extendFilter` code.

**Comment by jeanfredrik** [comment]
I tried using your fork @tremby , but I got `Cannot assign to read only property 'exports' of object '#<Object>'` runtime error with Storybook 5.1.11 and Webpack 4.39.2. It’s probably related to this: https://github.com/webpack/webpack/issues/4039

I have created my own fork and got it working for me: https://github.com/jfrk/twig-loader. It’s also available as `@jfrk/twig-loader` on NPM if it helps anyone else.

**Comment by JamesB797** [comment]
As others have observed it's possible to dump stuff in the compiler.js like this:

```js
    const output = [
      `var Twig = require("${pathToTwig}");
      ${jsonToConst('translations', options.translations)}
      ${functions}
      var template = Twig.twig(${JSON.stringify(opts)});
      module.exports = function(context) { return template.render(context); }`
    ];
```
