### ISSUE TITLE
How to include images with html-webpack-plugin + twig-loader?

### ISSUE THREAD

**Issue by evisotskiy** [zimmo-be/twig-loader#35]
Hi! I've created a question on the Stackoverflow about using your twig-loader with HtmlWebpackPlugin. Can you help me to find the answer?
It's a link on the question - https://stackoverflow.com/questions/47379405/how-to-include-images-with-html-webpack-plugin-twig-loader

**Comment by mortenson** [comment]
It seems like an OK way to go about this would be to chain `html-loader` -> `extract-loader` -> `twig-loader`, but that doesn't seem to work perfectly.

**Comment by evisotskiy** [comment]
Hello! Sorry for not responding in time, but I have already found a solution. I described my solution on stackoverflow, so you can read it there

**Comment by WhereJuly** [comment]
Thanks guys above for the hints 👍.

For the sake of someone needs the clearer solution (though for Vue CLI + `twig-loader` but easily translatable to general use with Webpack) see my [answer](https://stackoverflow.com/a/65250672/6597265) on StackOverflow. This engages `twig-loader`, `extract-loader` and `html-loader` and works with no issues.
