### ISSUE TITLE
Work with HtmlWebpackPlugin

### ISSUE THREAD

**Issue by mathieu-gilloots** [zimmo-be/twig-loader#36]
Hello,
I try to extract a dist index.html file (to use with critical webpack after), with HtmlWebpackPlugin and twig-loader.
My config : 
```
 module: {
        loaders: [
            { test: /\.twig$/, loader: "twig-loader" }
...
plugins: [
        new HtmlWebpackPlugin({
            template: path.resolve('./app/Resources/views/default/') + '/index.html.twig',
            filename: path.resolve('./web/dist/') + '/index.html',
            inject: true
        }),
```
It seem twig-loader does not do the thing, because in my generated index.html I've alway the extends, blocks, assets, .. tags.

Any ideas ?

Thanks,
Mathieu

**Comment by webberig** [comment]
This loader's purpose is to COMPILE twig templates, not actually RENDER them. If you are trying to render HTML during build-time, this loader is not the tool you need. 

Take a look at #21  for more details.

**Comment by radiocity** [comment]
Due to render purposes [twig-html-loader](https://github.com/radiocity/twig-html-loader) was created.
