### ISSUE TITLE
How to pass rendered output through to another loader?

### ISSUE THREAD

**Issue by tremby** [zimmo-be/twig-loader#37]
I want to render a template via the twig-loader and then pass the HTML generated through to html-loader so that any referenced images are imported (and so passed through my other loaders, such as url-loader), then output the result to a file. I've tried various combinations of extract-loader, apply-loader, twig-loader, html-loader, file-loader, and html-webpack-plugin but can't get anything working. The error messages are incredibly cryptic.

I don't mind if the twig file is an entry point or if it's referenced via html-webpack-plugin, or I just import the various page templates from a JS entry point. In any of those cases I'd need some way to pass context data to each template.

It looks like this was previously asked [elsewhere](https://github.com/zimmo-be/twig-loader/issues/21#issuecomment-259050169) but with no response.

**Comment by webberig** [comment]
Twig-loader's purpose is to COMPILE Twig templates, not render them. Its output is JS, not the actual HTML itself.

If you're trying to add raw HTML to your webpack build, and not the templates itself, twig-loader is not the proper tool.

I suggest you give [Apply-loader](https://github.com/mogelbrod/apply-loader) a try, as I suggested in the other issue you are referencing.

The module on which you add the apply-loader should use TwigJS directly (not twig-loader) to RENDER html.
