### ISSUE TITLE
Resolve paths

### ISSUE THREAD

**Issue by urbantrout** [zimmo-be/twig-loader#41]
I get an error when I want to extend a template file from another directory.

## Folder structure:
```
templates
↳ layouts
  ↳ _base.twig
↳ home
  ↳ _entry.twig
```
## Content for `templates/home/_entry.twig`:
```twig
{% extends 'layouts/_base' %}

{% block content %}
{% endblock %}
```

## Error Message: 
```
ERROR in ./templates/home/_entry.twig (./node_modules/html-webpack-plugin/lib/loader.js!./templates/home/_entry.twig)
Module not found: Error: Can't resolve 'layouts/_base' in '/Users/user/Projects/noyb/templates/home' @ ./templates/home/_entry.twig (./node_modules/html-webpack-plugin/lib/loader.js!./templates/home/_entry.twig) 1:0-24
```
Craft CMS (which uses Twig) does not complain about my setup.

I would love to keep my twig files untouched. Is there any way that twig-loader resolves all files inside a default_path (even without using namespaces)

**Comment by webberig** [comment]
A loader does not resolve files, twig-loader simply converts template references to require statements so webpack can resolve them.

You need to configure webpack to fit your resolving needs. Take a look at the docs here: https://webpack.js.org/configuration/resolve/

**Comment by ignism** [comment]
When resolving paths in webpack, twig is unable find the files.

**Comment by onceatime** [comment]
Same here looks that resolve doesnt work

**Comment by renestalder** [comment]
I also tried to use resolve.alias to resolve files absolute, but can't make it work. Anybody got this working with the twig-loader?

**Comment by drazik** [comment]
Same problem here. I added

```js
  config.resolve.modules = [
    ...config.resolve.modules,
    path.resolve(__dirname, "../templates"),
  ]
```

to my webpack config, but something like `{% import "components/Form/Input.html.twig %} as Input` fails to be resolved. Anybody found a solution?

**Comment by YoungElPaso** [comment]
Still doesn't work as far as I can tell. Works in twigjs-loader however.
