### ISSUE TITLE
{% include %} inside {% set %} does not work :(

### ISSUE THREAD

**Issue by tonystar** [zimmo-be/twig-loader#46]
I'm using Storybook.js + Twig.js (this setup: https://github.com/JungleMinds/JM_Basic-Twig-Project)

And {% include %} inside {% set %} does not work at all:
```
{% set content %}
  {% include '../../gallery/gallery-preview.twig' %}
{% endset %}
```
See source here: https://github.com/highweb/bricks-examples/blob/7536ee4ac057c0a6ff7e005d01a6682d086e00ed/gallery-carousel/gallery-carousel.twig#L16

Getting `"Unable to find template file ../../gallery/gallery-preview.twig"` error.

Any suggestions/ideas? Is it something related to #26?

**Comment by dubbs** [comment]
@tonystar I just figured this out.  See #54.
