### ISSUE TITLE
Spaceless tag deprecated.

### ISSUE THREAD

**Issue by hog-seruj** [zimmo-be/twig-loader#57]
The spaceless tag in "node_modules/twig-loader/test/fixtures/from/template.html.twig" at line 19 is deprecated since Twig 2.7, use the "spaceless" filter with the "apply" tag instead.

**Comment by webberig** [comment]
Since Twig.js still supports it (https://github.com/twigjs/twig.js/wiki/Implementation-Notes), I don't see a reason to remove those tags in our tests...

**Comment by andypost** [comment]
![IMG_20200816_180237](https://user-images.githubusercontent.com/73713/90337401-e8d78080-dfea-11ea-974c-1252daae03b2.jpg)

Thank you a lot! Since 0.5.5 it fixed
