### ISSUE TITLE
Disable caching

### ISSUE THREAD

**Issue by qur2** [zimmo-be/twig-loader#6]
Hi,

I'm trying to build some pages with webpack and twig-loader. However, webpack watch mode does not do a proper job. After messing around, I found out that all files are emitted correctly, but the payload is the same. I think it happens because of twig's cache and I would like to disable it, for development purpose. How can I achieve that? From the sources, it's not obvious to me.

Thanks.

**Comment by webberig** [comment]
Can you confirm that the templates are reloaded properly if you refresh the page ? Just making sure the problem is related to this check:
https://github.com/zimmo-be/twig-loader/blob/master/index.js#L70

I haven't found a way to manage the twig.js cache directly, I'll need to dig deeper in the code...

**Comment by qur2** [comment]
Hi, 

Reloading the page wouldn't help, I had to kill the process and restart it. 

I tried to add `Twig.cache(false)` but it didn't work. Now I see that line #70 and I guess that's why :) 
I suppose instead there should be some Twig utility to get a template, and then it would a matter of configuring Twig properly from the loader. 

What do you think?

**Comment by webberig** [comment]
I added that code because the library was throwing "Template already exists" exceptions.

This behavior is not documented, guess I'll need to figure out how I can replace/overwrite templates by digging into the twig.js code.

**Comment by qur2** [comment]
PR incoming

**Comment by webberig** [comment]
Any news on this ? Would you rather have me try to solve this ?

**Comment by qur2** [comment]
I think you should see the PR now. Apparently, I managed to PR to my own fork O.O

**Comment by DragorWW** [comment]
+1, problem with HtmlWebpackPlugin and webpack-dev-server

**Comment by DragorWW** [comment]
@qur2 @webberig I fix this problem.

**Comment by webberig** [comment]
PR #12 has been accepted and (hopefully) resolves this issue

**Comment by DragorWW** [comment]
@webberig I tested on a large project, all is well
