### ISSUE TITLE
Filtre Trans not working

### ISSUE THREAD

**Issue by chakib-lah** [zimmo-be/twig-loader#74]
Hello, i'm using twig-loader, and i need to use translation in my twig view, but i got this message error 
message: 'Unable to find filter trans', name: 'TwigException', type: 'TwigException'

 `    <p>{{ title }}</p>
     <p>{{ 'yes' | trans({}, 'global') }}</p>`

did you have the same probleme ?

**Comment by webberig** [comment]
You need to add filters to your code:
https://github.com/twigjs/twig.js/wiki/Extending-twig.js#filters
