### ISSUE TITLE
Rollup/Vite support

### ISSUE THREAD

**Issue by ay13** [zimmo-be/twig-loader#80]
Is there a port to Rollup/Vite planned?

**Comment by alex-lenk** [comment]
> Is there a port to Rollup/Vite planned?

They haven't updated the package for over three years.

I would like to update this package, the knowledge is there.

**Comment by webberig** [comment]
This repository contains just a [loader](https://webpack.js.org/concepts/#loaders) for webpack. If you need a plugin for a different builder, this should be a different repository.

Open to PR's if changes are needed to support newer webpack and/or twig.js versions.
