### ISSUE TITLE
Is it safe to assume that this project is not maintained anymore?

### ISSUE THREAD

**Issue by ericmorand** [zimmo-be/twig-loader#81]
There have been no change, no answer, no improvements for many years now.

Is this project abandoned?

**Comment by webberig** [comment]
Hi Eric,

We are still using this loader in production for our main product. The build is running as expected on Node 18 and Webpack 5. We are still maintaining our own product and if that would require changes to twig-loader, it will be updated. There simply has been no changes required for some time...

Can you elaborate on "no answer" ? Can't seem to find any issue or PR from you...

If you feel there are improvements required, feel free to create an issue or a PR.
